# Generated by Django 5.2.4 on 2025-08-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('sourcing', 'Sourcing'), ('processing', 'Processing'), ('packing', 'Packing'), ('shipping', 'Shipping'), ('delivery', 'Delivery'), ('retail', 'In Retail')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tracker.product')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
