# Generated by Django 5.2.4 on 2025-08-05 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_supplychainstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='tracked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
