# Generated by Django 5.2.4 on 2025-08-07 17:39

from django.db import migrations
from django.conf import settings

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group_name in settings.ROLE_PERMISSIONS.keys():
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_product_authorized_users'), # Should match your last migration file
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]