# Generated by Django 5.2.4 on 2025-08-10 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_populate_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(help_text='A unique identifier for this batch', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.AlterField(
            model_name='supplychainstep',
            name='stage',
            field=models.CharField(choices=[('sourcing', 'Sourcing'), ('manufacturing', 'Manufacturing'), ('processing', 'Processing'), ('packing', 'Packing'), ('shipping', 'Shipping'), ('delivery', 'Delivery'), ('retail', 'In Retail')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tracker.batch'),
        ),
    ]
