# Generated by Django 5.2.4 on 2025-08-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_batch_alter_supplychainstep_stage_product_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychainstep',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='step_documents/'),
        ),
    ]
