# Generated by Django 5.2.4 on 2025-08-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_supplychainstep_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychainstep',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplychainstep',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
